name: Build Project

on:
  push:
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Install gpg secret key
        run: |
          # Install GPG key
          cat <(echo -e "${{ secrets.OSSRH_GPG_KEY }}") | gpg --batch --import
          # Verify gpg secret key
          gpg --list-secret-keys --keyid-format=long
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots -Dgpg.passphrase=${{ secrets.OSSRH_GPG_KEY_PASSWORD }} verify

