name: Publish release to the Maven Central

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          cache: maven
      - name: Install gpg secret key
        run: |
          # Install GPG key
          cat <(echo -e "${{ secrets.OSSRH_GPG_KEY }}") | gpg --batch --import
          # Verify gpg secret key
          gpg --list-secret-keys --keyid-format=long
      - name: Publish package
        run: mvn --batch-mode -Dgpg.passphrase=${{ secrets.OSSRH_GPG_KEY_PASSWORD }} clean deploy -P release
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}